site_name: Velly Docs
nav:
  - Home: index.md
  - User Guide: user-guide.md
  - About:
    - Who we are?: about/who-we-are.md 
    - Privacy Policy: about/privacy-policy.md 
  - Donate: donate.md
# theme: readthedocs
